on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup tmate debug session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

    - name: Build container image
      run: |
        docker build \
        --tag ghcr.io/$GITHUB_ACTOR/vorta:$(echo $GITHUB_SHA | head -c7) \
        --tag ghcr.io/$GITHUB_ACTOR/vorta:latest \
        .

    - name: Container registry login
      run: >-
        echo "${{ secrets.GITHUB_TOKEN }}"
        | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
      
    - name: Push image to GitHub
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/$GITHUB_ACTOR/vorta:$(echo $GITHUB_SHA | head -c7)
        docker push ghcr.io/$GITHUB_ACTOR/vorta:latest